### ISSUE TITLE
globs issue

### ISSUE THREAD

**Issue by gemmell** [funkybob/serverless-s3-deploy#14]
Using your example configuration I get the following error:
```
YAMLException: unidentified alias "*/*.css" in "C:\tkbt\webapi\serverless.yml" at line 97, column 28:
                globs: **/*.css
                               ^
    at generateError (C:\Users\gemme\AppData\Roaming\npm\node_modules\serverless\node_modules\js-yaml\lib\js-yaml\loader.js:162:10)
    at throwError (C:\Users\gemme\AppData\Roaming\npm\node_modules\serverless\node_modules\js-yaml\lib\js-yaml\loader.js:168:9)
    at readAlias (C:\Users\gemme\AppData\Roaming\npm\node_modules\serverless\node_modules\js-yaml\lib\js-yaml\loader.js:1244:5)
    at composeNode (C:\Users\gemme\AppData\Roaming\npm\node_modules\serverless\node_modules\js-yaml\lib\js-yaml\loader.js:1336:20)
    at readBlockMapping (C:\Users\gemme\AppData\Roaming\npm\node_modules\serverless\node_modules\js-yaml\lib\js-yaml\loader.js:1057:11)
    at composeNode (C:\Users\gemme\AppData\Roaming\npm\node_modules\serverless\node_modules\js-yaml\lib\js-yaml\loader.js:1327:12)
    at readBlockSequence (C:\Users\gemme\AppData\Roaming\npm\node_modules\serverless\node_modules\js-yaml\lib\js-yaml\loader.js:925:5)
    at composeNode (C:\Users\gemme\AppData\Roaming\npm\node_modules\serverless\node_modules\js-yaml\lib\js-yaml\loader.js:1326:12)
    at readBlockMapping (C:\Users\gemme\AppData\Roaming\npm\node_modules\serverless\node_modules\js-yaml\lib\js-yaml\loader.js:1057:11)
    at composeNode (C:\Users\gemme\AppData\Roaming\npm\node_modules\serverless\node_modules\js-yaml\lib\js-yaml\loader.js:1327:12)
    at readBlockSequence (C:\Users\gemme\AppData\Roaming\npm\node_modules\serverless\node_modules\js-yaml\lib\js-yaml\loader.js:925:5)
    at composeNode (C:\Users\gemme\AppData\Roaming\npm\node_modules\serverless\node_modules\js-yaml\lib\js-yaml\loader.js:1326:12)
    at readBlockMapping (C:\Users\gemme\AppData\Roaming\npm\node_modules\serverless\node_modules\js-yaml\lib\js-yaml\loader.js:1057:11)
    at composeNode (C:\Users\gemme\AppData\Roaming\npm\node_modules\serverless\node_modules\js-yaml\lib\js-yaml\loader.js:1327:12)
    at readBlockMapping (C:\Users\gemme\AppData\Roaming\npm\node_modules\serverless\node_modules\js-yaml\lib\js-yaml\loader.js:1057:11)
    at composeNode (C:\Users\gemme\AppData\Roaming\npm\node_modules\serverless\node_modules\js-yaml\lib\js-yaml\loader.js:1327:12)
```

My configuration looks like:
```
...
plugins:
  - serverless-offline
  - serverless-s3-deploy
  
custom:
    assets:    
      targets:
       - bucket: mybucket
         files:
          - source: ../assets/
            globs: **/*.css
```

**Comment by gemmell** [comment]
Adding quotes around it works.

**Comment by funkybob** [comment]
Thanks! I've updated the README
