### ISSUE TITLE
Feature Request: Set Cache-Control and other Meta Data

### ISSUE THREAD

**Issue by arabold** [funkybob/serverless-s3-deploy#16]
It would be great if the plugin would allow setting meta data for the uploaded S3 files, specifically the `Cache-Control` header but others don't hurt either.

**Comment by funkybob** [comment]
Untested branch... please test and let me know how it goes!

**Comment by arabold** [comment]
Great! Thanks for the quick turnaround. Unfortunately it doesn't work on first try 😢 

Excerpt from my `serverless.yaml`:

```yaml
  # Deploy S3 Assets
  assets:
    auto: true # auto-deploy together with `serverless deploy`
    targets:
      - bucket: my-bucket
        prefix: ${self:custom.stage}/
        acl: public-read
        files:
          - source: ./dist
            globs:
              - '**/*'
            headers:
              CacheControl: max-age=31104000 # 1 year
```

Herer's the error call stack:
```
ServerlessError: There were 2 validation errors:
* MissingRequiredParameter: Missing required key 'Bucket' in params
* MissingRequiredParameter: Missing required key 'Key' in params
    at Response.req.send (/Users/xxxxxxxx/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:180:20)
    at Request.<anonymous> (/Users/xxxxxxxx/node_modules/aws-sdk/lib/request.js:364:18)
    at Request.callListeners (/Users/xxxxxxxx/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Users/xxxxxxxx/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/xxxxxxxx/node_modules/aws-sdk/lib/request.js:682:14)
    at Request.transition (/Users/xxxxxxxx/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/xxxxxxxx/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/xxxxxxxx/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/xxxxxxxx/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/xxxxxxxx/node_modules/aws-sdk/lib/request.js:684:12)
    at Request.callListeners (/Users/xxxxxxxx/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/Users/xxxxxxxx/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/xxxxxxxx/node_modules/aws-sdk/lib/request.js:682:14)
    at Request.transition (/Users/xxxxxxxx/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/xxxxxxxx/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/xxxxxxxx/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/xxxxxxxx/node_modules/aws-sdk/lib/request.js:35:11)
    at Request.<anonymous> (/Users/xxxxxxxx/node_modules/aws-sdk/lib/request.js:684:12)
    at Request.callListeners (/Users/xxxxxxxx/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at callNextListener (/Users/xxxxxxxx/node_modules/aws-sdk/lib/sequential_executor.js:95:12)
    at /Users/xxxxxxxx/node_modules/aws-sdk/lib/event_listeners.js:85:9
    at finish (/Users/xxxxxxxx/node_modules/aws-sdk/lib/config.js:315:7)
    at /Users/xxxxxxxx/node_modules/aws-sdk/lib/config.js:333:9
    at SharedIniFileCredentials.get (/Users/xxxxxxxx/node_modules/aws-sdk/lib/credentials.js:126:7)
    at getAsyncCredentials (/Users/xxxxxxxx/node_modules/aws-sdk/lib/config.js:327:24)
    at Config.getCredentials (/Users/xxxxxxxx/node_modules/aws-sdk/lib/config.js:347:9)
    at Request.VALIDATE_CREDENTIALS (/Users/xxxxxxxx/node_modules/aws-sdk/lib/event_listeners.js:80:26)
    at Request.callListeners (/Users/xxxxxxxx/node_modules/aws-sdk/lib/sequential_executor.js:101:18)
    at Request.emit (/Users/xxxxxxxx/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/xxxxxxxx/node_modules/aws-sdk/lib/request.js:682:14)
    at Request.transition (/Users/xxxxxxxx/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/xxxxxxxx/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at Request.runTo (/Users/xxxxxxxx/node_modules/aws-sdk/lib/request.js:403:15)
    at Request.send (/Users/xxxxxxxx/node_modules/aws-sdk/lib/request.js:367:10)
    at BbPromise (/Users/xxxxxxxx/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:168:13)
    at persistentRequest (/Users/xxxxxxxx/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:167:14)
    at doCall (/Users/xxxxxxxx/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:146:9)
    at BbPromise (/Users/xxxxxxxx/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:157:14)
From previous event:
    at persistentRequest (/Users/xxxxxxxx/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:144:38)
    at AwsProvider.request (/Users/xxxxxxxx/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:160:12)
    at glob.sync.forEach.filename (/Users/xxxxxxxx/node_modules/serverless-s3-deploy/index.js:104:27)
    at Array.forEach (native)
    at assets.files.forEach.opt (/Users/xxxxxxxx/node_modules/serverless-s3-deploy/index.js:89:37)
    at Array.forEach (native)
    at assetSets.forEach.assets (/Users/xxxxxxxx/node_modules/serverless-s3-deploy/index.js:78:22)
    at Array.forEach (native)
    at resolve (/Users/xxxxxxxx/node_modules/serverless-s3-deploy/index.js:75:17)
    at Assets.deployS3 (/Users/xxxxxxxx/node_modules/serverless-s3-deploy/index.js:74:12)
    at Assets.afterDeploy (/Users/xxxxxxxx/node_modules/serverless-s3-deploy/index.js:65:14)
```

However, looking through your code changes this error doesn't make much sense to me. I'll keep digging.

**Comment by arabold** [comment]
Oh my, found it: In the `index.js`, `Object.apply` in line 96 should probably be a `Object.assign` 😉 

After changing this locally everything works as expected. Thanks again for the quick turnaround of this feature! Very appreciated.


I'd suggest we also give an example how `headers` work as I had a couple of tries until it finally worked.

**Comment by funkybob** [comment]
Bad habit I inherited from ExtJS ... thanks! Fix pushed!

**Comment by funkybob** [comment]
Could you suggest an example to include in the docs, please?

**Comment by arabold** [comment]
Works perfectly and I saw you used my code from above as sample. Perfect! Thanks again.
