### ISSUE TITLE
List stack resources function does not work

### ISSUE THREAD

**Issue by Enase** [funkybob/serverless-s3-deploy#58]
Looks like serverless doesn't use bluebird promises anymore, so that plugin fails here:
https://github.com/funkybob/serverless-s3-deploy/blob/v0.9.0/index.js#L86

```
  TypeError: this.provider.request(...).then(...).return is not a function
      at Assets.listStackResources (/.../node_modules/serverless-s3-deploy/index.js:87:12)
      at Assets.deployS3 (/.../node_modules/serverless-s3-deploy/index.js:144:17)
      at Assets.afterDeploy (/.../node_modules/serverless-s3-deploy/index.js:69:19)

```

**Comment by ynx** [comment]
Can confirm that I ran into this issue too.
