### ISSUE TITLE
this.provider.request(...).then(...).return is not a function

### ISSUE THREAD

**Issue by kuindji** [funkybob/serverless-s3-deploy#60]
```
TypeError: this.provider.request(...).then(...).return is not a function
      at Assets.listStackResources (..../node_modules/serverless-s3-deploy/index.js:86:12)
      at Assets.deployS3 (..../node_modules/serverless-s3-deploy/index.js:143:17)
      at Assets.afterDeploy (..../node_modules/serverless-s3-deploy/index.js:69:19)
```

With assets: auto: true

Serverless version: 2.25.1

**Comment by GavL89** [comment]
I had this issue with the latest versions of serverless (2.28.3) and serverless-s3-deploy 0.9.0.  Upping the package version to 0.10.0 resolved the issue for me.
